Debian:
  pkgs:
    - apt-transport-https
    - python-apt
    - python-pip
  repo:
    url_base: https://download.docker.com/linux/{{ grains['os'] |lower }}
    key_url: https://download.docker.com/linux/{{ grains['os'] |lower }}/gpg
    version: {{ grains['oscodename'] |lower }}
    file: /etc/apt/sources.list.d/docker.list

RedHat:
  pkgs:
    - python2-pip
  repo:
    url_base: https://download.docker.com/linux/{{ grains['os'] |lower }}/{{ grains['osmajorrelease'] }}/$basearch/stable/
    key_url: https://download.docker.com/linux/{{ grains['os'] |lower }}/gpg
    version: {{ grains['oscodename'] |lower }}
    file: /etc/yum.repos.d/docker-ce.repo

Suse:
  pkg:
    name: docker
  pkgs:
    - python3-pip      #python 3 is default on OpenSUSE 15.0

